[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd app/backend && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd app/backend && npm run build"
]

[start]
cmd = "cd app/backend && node dist/main.js"

[variables]
NODE_ENV = "production"
