# Backend-specific Nixpacks configuration
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --only=production"]

[phases.build] 
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "node dist/main.js"

[variables]
NODE_ENV = "production"
PORT = "3001"
