import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateKeywordAnalyticsTables1758449341764 implements MigrationInterface {
    name = 'CreateKeywordAnalyticsTables1758449341764'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`idx_monthly_search_total\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_date\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`idx_base_keyword\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`idx_rank_position\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`unique_base_related_date\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`idx_period_type\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`idx_period_value\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_period\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_year\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_month_number\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_month_year\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_weekday_number\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_weekday_date\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_date\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_issue_type\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_date\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_analysis_date\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_keyword\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_primary_intent\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`unique_keyword_date\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`idx_base_query\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_collected_at\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_collection_type\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_pc\` \`monthly_search_pc\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_mobile\` \`monthly_search_mobile\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_total\` \`monthly_search_total\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_blog\` \`monthly_content_blog\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_cafe\` \`monthly_content_cafe\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_all\` \`monthly_content_all\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`estimated_search_yesterday\` \`estimated_search_yesterday\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`estimated_search_end_month\` \`estimated_search_end_month\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_blog\` \`saturation_index_blog\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_cafe\` \`saturation_index_cafe\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_all\` \`saturation_index_all\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`monthly_search_volume\` \`monthly_search_volume\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`blog_cumulative_posts\` \`blog_cumulative_posts\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`similarity_score\` \`similarity_score\` enum ('낮음', '보통', '높음') NOT NULL DEFAULT '보통'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` CHANGE \`search_volume\` \`search_volume\` bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`search_trends\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` CHANGE \`male_ratio\` \`male_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` CHANGE \`female_ratio\` \`female_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`issue_score\` \`issue_score\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`trend_direction\` \`trend_direction\` enum ('상승', '하락', '유지') NOT NULL DEFAULT '유지'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`volatility_score\` \`volatility_score\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`informational_ratio\` \`informational_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`commercial_ratio\` \`commercial_ratio\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`primary_intent\` \`primary_intent\` enum ('정보성', '상업성', '혼합') NOT NULL DEFAULT '혼합'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`confidence_score\` \`confidence_score\` decimal(5,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` DROP COLUMN \`collection_type\``);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` ADD \`collection_type\` enum ('trending', 'smartblock') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` CHANGE \`source_page\` \`source_page\` varchar(100) NOT NULL DEFAULT 'naver'`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` CHANGE \`rank_position\` \`rank_position\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` DROP COLUMN \`collected_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` ADD \`collected_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_cc02766e28b0fc2eb36646b073\` ON \`keyword_analytics\` (\`monthly_search_total\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_63ba2b7f9f3c64f867b41420eb\` ON \`keyword_analytics\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d5425b05be69813cf767e97c3f\` ON \`keyword_analytics\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_65bf9f8fbedfca420c54d80502\` ON \`keyword_analytics\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c94c5f788b1d7e8f7ef3884f19\` ON \`related_keywords\` (\`rank_position\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f9cf8e8e6212e0705957e5fb70\` ON \`related_keywords\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9f0998b08c8e2f9043153e6068\` ON \`related_keywords\` (\`base_keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_75a33e1f90ee9bd775649cbc2a\` ON \`related_keywords\` (\`base_keyword\`, \`related_keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ed4217bf57ecc11ae85fcc5aa0\` ON \`search_trends\` (\`period_value\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_50e5e0c0d6cf3123c9726225ed\` ON \`search_trends\` (\`period_type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1dbc403252e276b4c69130304e\` ON \`search_trends\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_50feb037785d4796b712f02f75\` ON \`search_trends\` (\`keyword\`, \`period_type\`, \`period_value\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a8472e8f7d6784f20bf5278108\` ON \`monthly_search_ratios\` (\`analysis_year\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a5c954cc377d88e14b5513a6e9\` ON \`monthly_search_ratios\` (\`month_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d08746c70d5e75b76cad655cd8\` ON \`monthly_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_50479c200ac3c5fb965ce6616b\` ON \`monthly_search_ratios\` (\`keyword\`, \`month_number\`, \`analysis_year\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_be448d76a6f97945d928d62990\` ON \`weekday_search_ratios\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8ca945118f08e5c1ed76cecebc\` ON \`weekday_search_ratios\` (\`weekday_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9cb72903909332fb07d0e70c39\` ON \`weekday_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f56a570bb40b7279390855f955\` ON \`weekday_search_ratios\` (\`keyword\`, \`weekday_number\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1c5e7b72635f456f721fb36328\` ON \`gender_search_ratios\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9700a1561e95c84e716637c79a\` ON \`gender_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f1c4dfaecc46a5c77d619fb500\` ON \`gender_search_ratios\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_56fa370a2117f82c30560f9182\` ON \`issue_analysis\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a22a1149fb62c7ff3471545f1b\` ON \`issue_analysis\` (\`issue_type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b299b20e909431455e07db1e3b\` ON \`issue_analysis\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b8c1e1dec92090538e20b2ee1f\` ON \`issue_analysis\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f56b73070909e4fecfc0228183\` ON \`intent_analysis\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4c89a71b1e951386c9bc157bdd\` ON \`intent_analysis\` (\`primary_intent\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_376d78a2a1d2cd6ae4052b9318\` ON \`intent_analysis\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_de07f9dc031e77284ec5136315\` ON \`intent_analysis\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_948d57f57801a927f4a44d8bb6\` ON \`keyword_collection_logs\` (\`collected_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d7ad20becadec69dd8fb895cd6\` ON \`keyword_collection_logs\` (\`collection_type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a7a58aef132dcd6e0617a8ea10\` ON \`keyword_collection_logs\` (\`base_query\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_a7a58aef132dcd6e0617a8ea10\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_d7ad20becadec69dd8fb895cd6\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_948d57f57801a927f4a44d8bb6\` ON \`keyword_collection_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_de07f9dc031e77284ec5136315\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_376d78a2a1d2cd6ae4052b9318\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c89a71b1e951386c9bc157bdd\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_f56b73070909e4fecfc0228183\` ON \`intent_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_b8c1e1dec92090538e20b2ee1f\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_b299b20e909431455e07db1e3b\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_a22a1149fb62c7ff3471545f1b\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_56fa370a2117f82c30560f9182\` ON \`issue_analysis\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1c4dfaecc46a5c77d619fb500\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_9700a1561e95c84e716637c79a\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_1c5e7b72635f456f721fb36328\` ON \`gender_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_f56a570bb40b7279390855f955\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_9cb72903909332fb07d0e70c39\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_8ca945118f08e5c1ed76cecebc\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_be448d76a6f97945d928d62990\` ON \`weekday_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_50479c200ac3c5fb965ce6616b\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_d08746c70d5e75b76cad655cd8\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_a5c954cc377d88e14b5513a6e9\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_a8472e8f7d6784f20bf5278108\` ON \`monthly_search_ratios\``);
        await queryRunner.query(`DROP INDEX \`IDX_50feb037785d4796b712f02f75\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`IDX_1dbc403252e276b4c69130304e\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`IDX_50e5e0c0d6cf3123c9726225ed\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`IDX_ed4217bf57ecc11ae85fcc5aa0\` ON \`search_trends\``);
        await queryRunner.query(`DROP INDEX \`IDX_75a33e1f90ee9bd775649cbc2a\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`IDX_9f0998b08c8e2f9043153e6068\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9cf8e8e6212e0705957e5fb70\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`IDX_c94c5f788b1d7e8f7ef3884f19\` ON \`related_keywords\``);
        await queryRunner.query(`DROP INDEX \`IDX_65bf9f8fbedfca420c54d80502\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`IDX_d5425b05be69813cf767e97c3f\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`IDX_63ba2b7f9f3c64f867b41420eb\` ON \`keyword_analytics\``);
        await queryRunner.query(`DROP INDEX \`IDX_cc02766e28b0fc2eb36646b073\` ON \`keyword_analytics\``);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` DROP COLUMN \`collected_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` ADD \`collected_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` CHANGE \`rank_position\` \`rank_position\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` CHANGE \`source_page\` \`source_page\` varchar(100) NULL DEFAULT 'naver'`);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` DROP COLUMN \`collection_type\``);
        await queryRunner.query(`ALTER TABLE \`keyword_collection_logs\` ADD \`collection_type\` varchar(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`confidence_score\` \`confidence_score\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`primary_intent\` \`primary_intent\` enum ('정보성', '상업성', '혼합') NULL DEFAULT '혼합'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`commercial_ratio\` \`commercial_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`intent_analysis\` CHANGE \`informational_ratio\` \`informational_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`volatility_score\` \`volatility_score\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`trend_direction\` \`trend_direction\` enum ('상승', '하락', '유지') NULL DEFAULT '유지'`);
        await queryRunner.query(`ALTER TABLE \`issue_analysis\` CHANGE \`issue_score\` \`issue_score\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` CHANGE \`female_ratio\` \`female_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`gender_search_ratios\` CHANGE \`male_ratio\` \`male_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`weekday_search_ratios\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`monthly_search_ratios\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`search_trends\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` CHANGE \`search_ratio\` \`search_ratio\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`search_trends\` CHANGE \`search_volume\` \`search_volume\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`similarity_score\` \`similarity_score\` enum ('낮음', '보통', '높음') NULL DEFAULT '보통'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`blog_cumulative_posts\` \`blog_cumulative_posts\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`related_keywords\` CHANGE \`monthly_search_volume\` \`monthly_search_volume\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_all\` \`saturation_index_all\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_cafe\` \`saturation_index_cafe\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`saturation_index_blog\` \`saturation_index_blog\` decimal(5,2) NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`estimated_search_end_month\` \`estimated_search_end_month\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`estimated_search_yesterday\` \`estimated_search_yesterday\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_all\` \`monthly_content_all\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_cafe\` \`monthly_content_cafe\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_content_blog\` \`monthly_content_blog\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_total\` \`monthly_search_total\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_mobile\` \`monthly_search_mobile\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`keyword_analytics\` CHANGE \`monthly_search_pc\` \`monthly_search_pc\` bigint NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE INDEX \`idx_collection_type\` ON \`keyword_collection_logs\` (\`collection_type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_collected_at\` ON \`keyword_collection_logs\` (\`collected_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_base_query\` ON \`keyword_collection_logs\` (\`base_query\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_date\` ON \`intent_analysis\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_primary_intent\` ON \`intent_analysis\` (\`primary_intent\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`intent_analysis\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`intent_analysis\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_date\` ON \`issue_analysis\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`issue_analysis\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_issue_type\` ON \`issue_analysis\` (\`issue_type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`issue_analysis\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_date\` ON \`gender_search_ratios\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`gender_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`gender_search_ratios\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_weekday_date\` ON \`weekday_search_ratios\` (\`keyword\`, \`weekday_number\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_weekday_number\` ON \`weekday_search_ratios\` (\`weekday_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`weekday_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`weekday_search_ratios\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_month_year\` ON \`monthly_search_ratios\` (\`keyword\`, \`month_number\`, \`analysis_year\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_month_number\` ON \`monthly_search_ratios\` (\`month_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`monthly_search_ratios\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_year\` ON \`monthly_search_ratios\` (\`analysis_year\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_period\` ON \`search_trends\` (\`keyword\`, \`period_type\`, \`period_value\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_period_value\` ON \`search_trends\` (\`period_value\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_period_type\` ON \`search_trends\` (\`period_type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`search_trends\` (\`keyword\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_base_related_date\` ON \`related_keywords\` (\`base_keyword\`, \`related_keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_rank_position\` ON \`related_keywords\` (\`rank_position\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_base_keyword\` ON \`related_keywords\` (\`base_keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`related_keywords\` (\`analysis_date\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_keyword_date\` ON \`keyword_analytics\` (\`keyword\`, \`analysis_date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_monthly_search_total\` ON \`keyword_analytics\` (\`monthly_search_total\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_keyword\` ON \`keyword_analytics\` (\`keyword\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_analysis_date\` ON \`keyword_analytics\` (\`analysis_date\`)`);
    }

}
